### ISSUE TITLE
Populate NIST models

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-nist#1]
The grammar is described but it's now time to populate the UML models here.

**Comment by opoudjis** [comment]
The grammar is only kind of described, and I would like you to approve the requirements model officially before I proceed with this, since requirements are meant to be a component of the entire metanorma model.  That means reviewing https://github.com/riboseinc/metanorma-standoc/issues/34 https://github.com/riboseinc/metanorma-ogc/issues/20

**Comment by ronaldtse** [comment]
The NIST model has been populated, I modeled it as close as possible to the NIST publication page and the NIST CSRC pages:

* https://www.nist.gov/publications
* https://csrc.nist.gov/publications/

@opoudjis can you help review this? Thanks!

**Comment by opoudjis** [comment]
I am doing this next. Kindly hold off on your dozen tickets about the NIST model until I have completed the review. As with ITU, the bibliographic modelling changes will impact the gem.

**Comment by ronaldtse** [comment]
The model is adequate and subject to issues raised in the other dozen tickets. Closing this in favor of the next ones.

**Comment by opoudjis** [comment]
1. I have not finished reviewing it, and I identified at least 1 mistake so far (title-intro can never be used for main title).

2. I do not have confidence that you have created issues for all the changes identified in the model, and in at least one instance you have rescinded an addition (topics).

This ticket is reopening.

**Comment by ronaldtse** [comment]
> I do not have confidence that you have created issues for all the changes identified in the model, and in at least one instance you have rescinded an addition (topics).

@opoudjis  I have not begun updating the model with the posted issues, so please help approach them as well.

**Comment by opoudjis** [comment]
Yes I will be updating the model as I go (already have been); it's cleaner for me to do so in tandem with the tasks, now that the model is in place.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !

**Comment by opoudjis** [comment]
All aspects of model reviewed against what had been keyed in so far.
