### ISSUE TITLE
NIST Pub "category" clarification

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-nist#10]
> Question: In the SP series, there are the categories of “Computer Security” vs “Information Security”. Are there other categories? In FIPS, there are also “subcategories” like “cryptography” under “computer security”. Yet non CSRC documents don’t seem to have them.
 
> NIST: This is a legacy artifact.

Basically, the categories (e.g. two SP 800 categories "Computer Security", "Information Security") should remain free text. Other SP sub-series have their own categories (e.g. SP 500 is “Computer Systems Technology”)

Action: update model and corresponding gem.

**Comment by opoudjis** [comment]
They have been left as secondary series (document attribute "subseries"), and the vocabulary will be updated as more subseries come to light. The proposal for them to be free text is not particularly meaningful: that free text does have to end up as an element in `/bibdata` somewhere, and that might as well be the series container. Has already been addressed in #9.
