### ISSUE TITLE
NIST Pub URL clarification

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-nist#12]
> Question: There is always a “Current URL”, nearly always a “URL”, and often a DOI link. (This is from the CRSC Excel list)

Answer: the "Current URL" and "URL" can change, so we should not include them in the NIST Bib model. The DOI should be kept in the model.

Action: Update model and gem.

**Comment by ronaldtse** [comment]
New confirmation -- we want to keep the "Current URL".

See https://github.com/metanorma/metanorma-nist/issues/58

**Comment by opoudjis** [comment]
So, there are two URLs: `:url:` and `:doi:`. The current-url/url distinction no longer obtains.

**Comment by ronaldtse** [comment]
Yes.

**Comment by opoudjis** [comment]
You have omitted the doc-email (email contact for document), which is needed for templates. Putting that in too.
