### ISSUE TITLE
Remove `NistSpSeriesEnum`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-nist#13]
There is no `NistSpSeriesEnum`, as it was described, "Computer Security" and "Information Security" function as pure labels, they are not intended to be sub-series.

**Comment by opoudjis** [comment]
We've already discussed this: I do not see that logically there is anything else to call these. "Label" is simply not good enough in a bibliographic model, and if they are not series of documents, and they are not technical committees, then someone will need to tell me what they are.

**Comment by opoudjis** [comment]
To be more explicit: to me, a label that groups together a set of documents is, conceptually, a series. That's the best way to think of monograph series. I do not believe that series are necessarily an ordered set of publications (hence they can belong to a Computer Security series without receiving a series number.)

**Comment by ronaldtse** [comment]
"Computer Security" and and "Information Security" are textual labels. They do not need to be in `BibData`. They are not used to group anything.

A "Series" in the NIST publication sense is just a way of grouping documents. It's not a periodic serial.

**Comment by opoudjis** [comment]
*Buries head in hands.*

If "Computer Security" and "Information Security" are not in bibdata, how are they going to end up in the document? They have to be *somewhere* in the XML. And they have to be modelled as something. "Label" is not modelling.

And I've just said: I don't believe series should be restricted to periodic series at all. Following ISO 690, a series *is* just a way of grouping documents. Which means bibdata/series applies.

ISO 690:

> 2.28
> series
> monographic series
> group of separate information resources (2.12) related to one another by the fact that each information resource bears, in addition to its own title proper, a collective title applying to the group as a whole

**Comment by opoudjis** [comment]
Is there any online material where the nature of these labels is specified?

**Comment by opoudjis** [comment]
Fine, I'll call it `title[@type = document-class]`

**Comment by ronaldtse** [comment]
@opoudjis agree! Thanks!
