### ISSUE TITLE
Modeling of states: Withdrawn, Withdrawn announced, and Retired

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-nist#15]
To model them we can use bibliographic dates:

* Withdrawn date
* Withdrawn announced date
* Retired date

If a draft/document has Retired date, it will be or has been retired.

If a draft/document has a withdrawn date, it is either withdrawn (if date in past) or withdrawn announced (if date in future).

Or is it better implemented as document stages? Maybe not...?

**Comment by opoudjis** [comment]
No, we will stick with the stages we have, and we will use dates to model these transitions: withdrawn vs withdrawn-announced are not distinct states (a withdrawn-announced public draft is still a public draft right now), and the dates are required anyway.

The withdrawn date is identical to the withdrawn announced date, the only difference is that the first is in the past and the second is in the future.

We need to stick with relaton vocabulary for the dates. withdrawn is obsoleted-date. retired is the new abandoned-date.

**Comment by ronaldtse** [comment]
OK. Note that the authoritative states are described here: https://github.com/metanorma/metanorma-nist/issues/94 .

**Comment by opoudjis** [comment]
As far as I'm concerned, they're described in https://github.com/metanorma/metanorma-nist/issues/90
