### ISSUE TITLE
Implement NIST document stages

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-nist#16]
This is the near-final stage table (with mapping to ISO Harmonized Stages).

We should support it in the model, and also include this in documentation.

| ISO stage      | NIST stage        | 93 Repeat current phase | 98 Abandon     | 99 Proceed
|---|---|---|---|---
| 00 Preliminary | draft-internal    |                         | (stop work)    | draft-wip, draft-public, or final (amend)
| 10 Proposal    | draft-wip         |                         | draft-retire   | draft-withdrawn
| 20 Preparatory | draft-prelim      |                         | draft-retire   | draft-withdrawn
| 40 Enquiry     | draft-public      | 2PD, 3PD, ... FPD           | draft-retire   | draft-withdrawn
| 50 Approval    | (NIST ERB review) |                         | draft-retire   | final
| 60 Publication | final             |                         |                |
| 90 Review      | final-review      | final (confirm)         | final-withdrawn| draft-internal (revise or amend)
| 95 Withdrawal  | final-withdrawn   |                         |

**Comment by opoudjis** [comment]
Since this involves the same states as before, I don't know what you are expecting me to do with this.

Do you want me to include the NIST table in documentation? Including NIST process documentation in Metanorma documentation is obviously a bad idea, since NIST, not Metanorma, are responsible for it.

I am also assuming that "(NIST ERB review)" is not a distinct state, and that "final (confirm)" is just "final" as a state.

**Comment by opoudjis** [comment]
I have just realised that a draft can be both retired or withdrawn, and internal/wip/prelim/public.

This means that you have misled me above. It is impossible to use draft-retire as the document status, because that is mutually exclusive with the status that selects the appropriate cover page in #100.

Thanks a bunch.

The alternative of encoding status atomically, as draft-wip-retire and draft-public-withdrawn, is rejected as stupid. I am forced to use a substage convention, as is done (for the same reason) in ISO.

I would ask you to confirm, but I won't. If they want to see draft-retire as a status, they can see it as an output manipulation.

**Comment by opoudjis** [comment]
So the actual statuses are as follows: "retired" and "withdrawn" are substages.


| ISO stage      | NIST stage        | 93 Repeat current phase | 98 Abandon     | 99 Proceed
|---|---|---|---|---
| 00 Preliminary | draft-internal    |                         | (stop work)    | draft-wip, draft-public, or final (amend)
| 10 Proposal    | draft-wip         |                         | draft-wip, retired   | draft-wip, withdrawn
| 20 Preparatory | draft-prelim      |                         | draft-prelim, retired   | draft-wip, withdrawn
| 40 Enquiry     | draft-public      | 2PD, 3PD, ... FPD           | draft-public, retired   | draft-public, withdrawn
| 50 Approval    | **(NIST ERB review)** |                         | **draft-public, retired**   | final
| 60 Publication | final             |                         |                |
| 90 Review      | final-review      | **final (confirm)**         | final, withdrawn | draft-internal (revise or amend)
| 95 Withdrawal  | final, withdrawn   |                         |                


The boldfaced entries need confirmation:

* NIST ERB review: is this a distinct status? If not, neither is 50-98 "draft-public, retired"
* final (confirm): Is the "(confirm)" in brackets a status indication, or just an annotation inserted to confuse me?

**Comment by opoudjis** [comment]
NistBib, it turns out, uses the ISO stage numbers for stage and substage. I will continue to use the text values given up for bibdata.

**Comment by opoudjis** [comment]
Implemented stage and substage.

**Comment by opoudjis** [comment]
Done table of transitions in README. Still require answers re NIST ERB review. I've modelled "final (confirm)" as final with use of the confirmed-date attribute.

**Comment by ronaldtse** [comment]
> Do you want me to include the NIST table in documentation? Including NIST process documentation in Metanorma documentation is obviously a bad idea, since NIST, not Metanorma, are responsible for it.

Yes, we want to include this table in documentation. I know what you mean, but it is crucial for NIST Metanorma users to be aware of the permitted states and transitions for his/her document. It is necessary we mirror their stages in documentation.


> I have just realised that a draft can be both retired or withdrawn, and internal/wip/prelim/public.

Yes it has been described in a number of places -- cover "on top".

> NIST ERB review: is this a distinct status? If not, neither is 50-98 "draft-public, retired"

Yes, it is a distinct status of the PROJECT, not of the document. So it does not have to be implemented in the document now. (Ideally there could be a "ERB review passed" label on the document)

> final (confirm): Is the "(confirm)" in brackets a status indication, or just an annotation inserted to confuse me?

This stage modifies the document into a "confirmed" document which contains the "Publication is current as of <date>" on cover page.

-----

In detail, here is the NIST 5-year review process:

We have begun a process to more regularly review our SP 800s every 5 years, so we could potentially have a “final-review” stage. Possible outcomes are:

* Withdraw Immediately: (“final-withdrawn”)
* Withdraw: (“final-withdrawn”)
* Convert: (“final-withdrawn”) Withdraw, and replace with a different publication(s) (i.e., different pub # altogether)
* Revise: develop a new draft and release it for public comment (go to “draft-internal” and then either “draft-wip” or “draft-public”)
* Amend: issue an updated “final”, no public comment period; minor changes (errata update); keep pub # and rev # as-is
* Confirm: keep as-is; add statement on Title page, under the date: Publication is current as of <date>. [Note that this is a new feature we have talked about with the Library, but which haven’t implemented yet.]

We should update our documentation to describe this as well.

**Comment by opoudjis** [comment]
> We should update our documentation to describe this as well.

No. If NIST want process documentation, they need to provide it. I will not be writing documentation for them, from scratch, for processes I have no visibility over. And the foregoing is not acceptable: it is too informal ("we have begun", "different pub #"), too tentative ("we could potentially"), and too decontextualised.

**Comment by opoudjis** [comment]
This issue has been implemented. `final (confirm)` is merely a final state document with a confirmed date, it does not need a distinct state.
