### ISSUE TITLE
Align with gem practice: NIST Pub document section structure

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-nist#2]
> A NIST Pub document always has a “preface”, an “introduction”, multiple sections, and multiple (but optional) annexes.

Confirmed. We need to ensure we have this in metanorma-nist.

**Comment by opoudjis** [comment]
We have multiple sections and multiple but optional annexes. We have a multifarious preface section.

The introduction is in fact a normal section, numbered and treated like all other sections. Metanorma XML should not tag this as `<introduction>`, as distinct from `<clause><title>Introduction</title>`: that will break things, and in any case Metanorma XML restricts Introductions to be prefatory, not a main section. Rather, introductions should be validated the same way Scope is validated in metanorma-iso: ensuring that the first section in the body of the document is called Introduction.

Implementing this validation behaviour.
