### ISSUE TITLE
NIST Pub title does not allow Part title

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-nist#4]
> Question: A NIST Pub document title can be composed of 3 elements: Main title, Sub-title, and the Part title. (e.g. SP 800-57 Part 2 Rev. 1 has a Part title)
 
> NIST: Only Main title and Sub-title. There are 1 or 2 examples where a part title was repeated in the subtitle.  We should not be allowing for this, moving forward.

Action: update model and gem.

**Comment by opoudjis** [comment]
Has just been done.
