### ISSUE TITLE
Relaton: superseding NIST Pubs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-nist#7]
> Question: A NIST Pub can “supersede” another document (e.g. https://www.nist.gov/publications/personal-identity-verification-piv-federal-employees-and-contractors)
 
> NIST: Yes. A pub may actually supersede one or more publications (e.g., https://csrc.nist.gov/publications/detail/sp/800-53a/archive/2008-07-01), or be superseded by one or more pubs (e.g., https://csrc.nist.gov/publications/detail/sp/800-26/archive/2001-11-01).

Action: Allow specifying in NIST pub the necessary bib-relations (think IETF RFC `supersedes`). There is no need to update the model since it is already supported.

**Comment by ronaldtse** [comment]
This is also related to https://github.com/metanorma/metanorma-nist/issues/79

**Comment by opoudjis** [comment]
Calling it `:obsoletes:`, since that is the relaton term, and the document attribute is already used in GB.

**Comment by opoudjis** [comment]
Adding `:obsoleted-by:` for the converse. 

NIST needs a consistent way of referencing specific editions of documents. That is in place now with revisions, e.g. _SP 800-53A Rev. 1_, but I am concerned to see identifiers such as "NISTIR 6885 2003 Edition". Is that a tractable identifier string that can be queried via NIST?

**Comment by opoudjis** [comment]
Implementing, but will leave open pending nistbib integration. Once nistbib is available, we will use nistbib to fetch the title of the referenced documents, their revision dates, and other information which NIST require in rendering.

**Comment by ronaldtse** [comment]
I see what you mean now by `NISTIR 6885 2003 Edition`. Gotta ask.

**Comment by opoudjis** [comment]
@ronaldtse Have you asked? This is not an problem specific to this issue, but to nistbib in general.

**Comment by opoudjis** [comment]
Am now getting details of superseded and obsoleted references from nistbib, and reading them into XML output.
