### ISSUE TITLE
NIST Pubs valid document states

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-nist#8]
> Question: The valid "document states” are “final”, “public-draft”, “retired-draft”, “withdrawn” and “private-draft” (The first 4 are from the CRSC Excel list, I imagined that at least “private-draft” also exists since there is a “public-draft”). In addition, each of these stages can have an “iteration” number (I saw that there are “2nd drafts”) (ISO documents have this too).
 
> NIST: This is less standardized—sometimes there are “initial public drafts” and “final public drafts”. If we have not released a draft for public comment, it’s typically referred to as an “internal draft” but this is not standard, nor is any version numbering for those internal drafts.

Action: We will standardize this as the following states, subject to discussions:

* internal-draft
* public-draft 
  * @opoudjis can we use `iteration`s to model initial-public-draft (that's iteration 1) and final-public-draft?
* final
* retired-draft
* withdrawn

**Comment by opoudjis** [comment]
> can we use iterations to model initial-public-draft (that's iteration 1) and final-public-draft?

I don't see why not, it's just a matter of a conditional in the template. The response implies they would like wiggle room; we can pass through whatever state they put through, and I'm not convinced they have even formalised the distinction between initial and final drafts.

**Comment by opoudjis** [comment]
Actually, I will allow text in the iteration, so they can put in the string "final".

**Comment by ronaldtse** [comment]
Awesome. Thanks!
