### ISSUE TITLE
NIST Pub "pub series" clarification

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-nist#9]
> Question: Each NIST Pub must belong to a Pub Series, these are the “NIST AMS”, “NIST GCR”, “NIST FIPS” and “NIST SP” (These are from the NIST Publications Advanced Search interface). While “SP 800” and “SP 1500” are sub-series on their own, maybe it’s not necessary to model them, but we can just put them in the “document number” (e.g. series = “NIST SP”, document number = “800-179 Rev. 1”)
 
> NIST: Let's keep the series “NIST SP” separate from the publication number “800-179…”

Action: update model and corresponding gem.

**Comment by opoudjis** [comment]
The model gives both series and type as being of type NistPubSeries. Clearly the latter is not of type NistPubSeries, and is meant to be instead of a coarse-grained enumeration like "standards", "reports", etc. I am assuming that the latter is only populated with "standards" until told differently; the NistPubSeries vocabulary is too large to be useful for document types.

**Comment by ronaldtse** [comment]
@opoudjis 

1. We will get rid of NistSpSeries and keeping NistPubSeries. The information of NistSpSeries will be manual free-form text supplied by a document attribute.
2. `type: NistPubSeries` is an obvious error, it should be removed.

**Comment by opoudjis** [comment]
The writeup above implies that we will infer what is currently the prefix to docnumber, SP AMS FIPS AMS, from the document series. For that to work, I need an abbreviation equivalent for *all* the legal series titles. I am missing equivalents for Building Science Series, ITL Bulletin, Letter Circular, Product Standards, Other, CSRS White Paper, CSRC Book, CSRC Use Case, CSRC Building Block. I propose to just use the phrase as is for those series titles.

**Comment by ronaldtse** [comment]
Actually, there is no “type” in a NIST pub, only the series. In the SP series, they do not distinguish “standard” vs “guidelines” etc.

**Comment by opoudjis** [comment]
Well, doctype is optional, so we'll just never set it.

**Comment by opoudjis** [comment]
Implemented docidentifier composition: if the docidentifier document attribute is not provided, the gem will infer the document identifier from a combination of the series abbreviation, the document number, the edition and the part.

**Comment by opoudjis** [comment]
The subseries will end up being modelled as a series container anyway, so the fact it is provided to Asciidoctor as a free text container is neither here nor there. I will differentiate the two series as main vs secondary in the XML.

**Comment by ronaldtse** [comment]
@opoudjis are you sure we want to model the sub-series? I'm just afraid it becomes complicated.

There are SP 800, SP 500, SP 1500 and SP 1800. There may be more that I'm not aware of. If they make a new SP 900, we need to handle that without having to change code?

**Comment by opoudjis** [comment]
The subseries are Information Security and Computer Security. I am not modelling 800, 500, 1500, 1800.

**Comment by ronaldtse** [comment]
It’s not right — “computer security” and “information security” are merely “labels” of documents within the series “SP 800”. They look like sub-sub-series, but they are not. 

And it was said that these two labels are now considered arbitrary and therefore should be thought of as free text. 

They are not to be modeled — just a free text document attribute will do.

**Comment by opoudjis** [comment]
But that does not help me. What *are* they? They can't just be "labels". And if they are a subdivision of NIST SP documents, that satisfies the definition of a subseries.

Not modelling them, I'm afraid, is nonsense: anything that ends up in the front page of output has to be captured in the XML, and anything captured in the XML has to be modelled and semantically accounted for.

**Comment by ronaldtse** [comment]
*They* ("Computer Security", "Information Security") are just labels. They do not specify "subdivisions".

The story was that SP 800 originally says "Computer Security". Then some author thought more generic information security is not "Computer Security", so replaced it with "Information Security". Then copy/paste of templates led to now there are "Computer Security" and "Information Security".

So they do have meaning, but it was never sanctioned until it was too late. And now we treat them only as a label.
